### ISSUE TITLE
HAPI Lack of Support for GEO_PrimVolume::StorageType::VOLUME_TYPE_VECTOR(x) and HAPI_VolumeVisualType::HAPI_VOLUMEVISTYPE_IMAGE

### ISSUE THREAD

**Issue by ChildAdrian** [sideeffects/HoudiniEngineSample#1]
Houdini 20.0.547, though houdini 20 does support storing volume pixel as vectors and "image" visualmode

1. HAPI seens out of date with HAPI_VolumeVisualType, should add HAPI_VolumeVisualType::HAPI_VOLUMEVISTYPE_IMAGE
2. When HoudiniApi::GetVolumeInfo on a Vector storage type volume in houdini 20.0.547, the HAPI_VolumeInfo::tupleSize always been 1, this is Wrong!
3. Session will crash when call HoudiniApi::GetHeightFieldData vector volume type.

**Comment by rajatg-sidefx** [comment]
Hi there,
As this is not specific to the HoudiniEngineSample, we recommend reporting the issue with our support team at [support@sidefx.com](mailto:support@sidefx.com).

I see an entry for it has already been made in our internal bug database and I will be closing this issue here.
